blog/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin
from blog import views as blog_views

urlpatterns = patterns('',
    # Blog urls
    url(r'^page/(?P<page>\d+)/?$', blog_views.BlogPage.as_view(), name='blog_page'),
    url(r'^post/(?P<slug>.+)/?$', blog_views.PostPage.as_view(), name='blog_post'),
    url(r'^add/?$', blog_views.PostAddPage.as_view(), name='post_add'),

    # AJAX urls
)

palindrome/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from palindrome import views as palindrome_views

urlpatterns = patterns('',
    # Blog urls
    url(r'^$', palindrome_views.HomePage.as_view(), name='home'),
    url(r'^result/?$', palindrome_views.ResultPage.as_view(), name='result'),

    # AJAX urls
)

pirsipy_test/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from core import views as core_views
from blog import views as blog_views
from pirsipy_test import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Internationalization
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Home
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    # App urls
    url(r'^auth/', include('accounts.urls', namespace='accounts')),
    url(r'^(?P<username>[-\w]+)/blog/', include('blog.urls', namespace='blog')),
    url(r'^palindrome/', include('palindrome.urls', namespace='palindrome')),
    # Social auth
    url(r'^sa/', include('social.apps.django_app.urls', namespace='social')),
    # Other urls
    url(r'^blog/?$', blog_views.Blog.as_view(), name='blog_home'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palindrome/models.py
# coding=utf-8

__author__ = 'meloman'

palindrome/forms.py
# coding=utf-8

from django import forms
from django.utils.translation import ugettext_lazy as _l, ugettext as _

__author__ = 'meloman'


class PalindromeForm(forms.Form):
    """ Palindrome form """
    string = forms.CharField(
        # Translators: Форма палиндрома. Поле ввода предложения
        label=_l(u'palindrome_form_string'),
        required=True,
        max_length=100,
        initial=u'',
        widget=forms.TextInput(attrs={
            # Translators: Форма палиндрома. Поле ввода предложения. Плейсхолдер
            'placeholder': _l(u'palindrome_form_string_placeholder'),
        })
    )

palindrome/views.py
# coding=utf-8

from django.utils.decorators import method_decorator

from django.views.generic import TemplateView
from palindrome.forms import PalindromeForm
from utils.decorators import render_to

__author__ = 'meloman'


def _palindrome_test(string):
    return string.lower().strip() == string.lower().strip()[::-1]


class HomePage(TemplateView):
    template_name = 'palindrome/home.html'

    @method_decorator(render_to(template_name))
    def get(self, request, *args, **kwargs):
        return {'form': PalindromeForm()}


class ResultPage(TemplateView):
    template_name = 'palindrome/result.html'

    @method_decorator(render_to(template_name))
    def post(self, request, *args, **kwargs):
        form = PalindromeForm(request.POST)
        data = None
        if form.is_valid():
            data = form.cleaned_data
        return {'palindrome': _palindrome_test(data['string']) if data else False}

templates/palindrome/home.html
{% extends '_base.html' %}

{% load bootstrap3 %}
{% load i18n %}



{% block content %}
    <div class="palindrome-block">
        <div class="block-wrapper">
            <form action="{% url 'palindrome:result' %}" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <a href="{% url 'home' %}" class="btn btn-primary">
                    {# Translators: Палиндром. Главная страница. Кнопка назад #}
                    {% trans 'palindrome_home_page_back_button' %}
                </a>
                <button type="submit" class="btn btn-success">
                    {# Translators: Палиндром. Главная страница. Кнопка проверить #}
                    {% trans 'palindrome_home_page_test_button' %}
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/palindrome/result.html
{% extends '_base.html' %}

{% load bootstrap3 %}
{% load i18n %}



{% block content %}
    <div class="result-block">
        <div class="block-wrapper">
            <div>
                <div class="result-text">
                    {% if palindrome %}
                        {# Translators: Палиндром. Страница результата. Текст результата #}
                        {% trans 'palindrome_result_page_true_result' %}
                    {% else %}
                        {# Translators: Палиндром. Страница результата. Текст результата #}
                        {% trans 'palindrome_result_page_false_result' %}
                    {% endif %}
                </div>
                <a href="{% url 'palindrome:home' %}" class="btn btn-primary">
                    {# Translators: Палиндром. Страница результата. Кнопка назад #}
                    {% trans 'palindrome_result_page_back_button' %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}