accounts/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from accounts import views as accounts_views

__author__ = 'meloman'


urlpatterns = patterns('',
    # Auth urls
    url(r'^login/?$', accounts_views.Login.as_view(), name='login'),
    url(r'^logout/?$', accounts_views.Logout.as_view(), name='logout'),

    # AJAX urls
)

blog/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin
from blog import views as blog_views

urlpatterns = patterns('',
    # Blog urls
    url(r'^page/(?P<page>\d+)/?$', blog_views.BlogPage.as_view(), name='blog_page'),
    url(r'^post/(?P<slug>.+)/?$', blog_views.PostPage.as_view(), name='blog_post'),
    url(r'^add/?$', blog_views.PostAddPage.as_view(), name='post_add'),

    # AJAX urls
)

pirsipy_test/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from core import views as core_views
from blog import views as blog_views
from pirsipy_test import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Internationalization
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Home
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    # App urls
    url(r'^auth/', include('accounts.urls', namespace='accounts')),
    url(r'^(?P<username>[-\w]+)/blog/', include('blog.urls', namespace='blog')),
    url(r'^palindrome/', include('palindrome.urls', namespace='palindrome')),
    # Social auth
    url(r'^sa/', include('social.apps.django_app.urls', namespace='social')),
    # Other urls
    url(r'^blog/?$', blog_views.Blog.as_view(), name='blog_home'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
# coding=utf-8

__author__ = 'meloman'

core/views.py
# coding=utf-8

import logging
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from utils.decorators import render_to

__author__ = 'meloman'
logger = logging.getLogger(__name__)


class HomePage(TemplateView):
    template_name = 'core/home.html'

    @method_decorator(render_to(template_name))
    def get(self, request, *args, **kwargs):
        return {}

templates/core/home.html
{% extends '_base.html' %}

{% load bootstrap3 %}
{% load i18n %}



{% block header %}{% endblock %}

{% block content %}
    <div class="core-home-block">
        <div class="block-wrapper">
            <a href="{% url 'palindrome:home' %}" class="btn btn-lg btn-primary">
                {# Translators: Домашняя страница. Кнопка палиндрома #}
                {% trans 'home_page_palindrome_button' %}
            </a>
            <a href="{% if user.is_authenticated %}{% url 'blog:blog_page' user.username 1 %}{% else %}{% url 'accounts:login'%}{% endif %}" class="btn btn-lg btn-primary">
                {# Translators: Домашняя страница. Кнопка блога #}
                {% trans 'home_page_blog_button' %}
            </a>
            <a href="https://github.com/Seg-mel/pirsipy_test" class="github-link" target="_blank">
                {# Translators: Домашняя страница. Ссылка на github #}
                {% trans 'home_page_github_link' %}
            </a>
            <a href="https://bitbucket.org/Seg-mel/pirsipy_test/" class="github-link" target="_blank">
                {# Translators: Домашняя страница. Ссылка на bitbucket #}
                {% trans 'home_page_bitbucket_link' %}
            </a>
        </div>
    </div>
{% endblock %}

{% block footer %}{% endblock %}