accounts/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from accounts import views as accounts_views

__author__ = 'meloman'


urlpatterns = patterns('',
    # Auth urls
    url(r'^login/?$', accounts_views.Login.as_view(), name='login'),
    url(r'^logout/?$', accounts_views.Logout.as_view(), name='logout'),

    # AJAX urls
)

blog/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin
from blog import views as blog_views

urlpatterns = patterns('',
    # Blog urls
    url(r'^page/(?P<page>\d+)/?$', blog_views.BlogPage.as_view(), name='blog_page'),
    url(r'^post/(?P<slug>.+)/?$', blog_views.PostPage.as_view(), name='blog_post'),
    url(r'^add/?$', blog_views.PostAddPage.as_view(), name='post_add'),

    # AJAX urls
)

pirsipy_test/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin

from core import views as core_views
from blog import views as blog_views
from pirsipy_test import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Admin
    url(r'^admin/', include(admin.site.urls)),
    # Internationalization
    url(r'^i18n/', include('django.conf.urls.i18n')),
    # Home
    url(r'^$', core_views.HomePage.as_view(), name='home'),
    # App urls
    url(r'^auth/', include('accounts.urls', namespace='accounts')),
    url(r'^(?P<username>[-\w]+)/blog/', include('blog.urls', namespace='blog')),
    url(r'^palindrome/', include('palindrome.urls', namespace='palindrome')),
    # Social auth
    url(r'^sa/', include('social.apps.django_app.urls', namespace='social')),
    # Other urls
    url(r'^blog/?$', blog_views.Blog.as_view(), name='blog_home'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# coding=utf-8

from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _l, ugettext as _
from django.db import models
from os import path
from pytils.translit import slugify

__author__ = 'meloman'


class Post(models.Model):
    """ Post of blog model """

    def upload_to_path(instance, filename):
        filename_list = filename.split('.')
        if len(filename_list) > 1:
            file_name = ''.join(filename_list[:-1])
            file_ext = filename_list[-1]
            slug_file_name = '.'.join([slugify(file_name), file_ext])
        else:
            file_name = ''.join(filename_list)
            slug_file_name = ''.join([slugify(file_name)])
        return path.join('blogs', instance.author.username, slug_file_name)

    # Translators: Модель поста. Поле заголовка
    title = models.CharField(_l(u'post_title'), max_length=50)
    # Translators: Модель поста. Поле слага
    slug = models.CharField(_l(u'post_slug'), max_length=50)
    # Translators: Модель поста. Поле короткого содержания
    short_body = models.CharField(_l(u'post_short_body'), max_length=200)
    # Translators: Модель поста. Поле содержания
    body = models.TextField(_l(u'post_body'))
    author = models.ForeignKey(User)
    # Translators: Модель поста. Поле даты создания
    created = models.DateField(_l(u'post_created'), auto_now_add=True)
    # Translators: Модель поста. Поле изображения
    image = models.ImageField(_l(u'post_image'), upload_to=upload_to_path)

    def __unicode__(self):
        return unicode(u'#{id} [{user}] {title}'.format(id=self.id, user=self.author.username, title=self.title))

    class Meta:
        ordering = ('author', 'id')

blog/forms.py
# coding=utf-8

from django import forms
from blog.models import Post

__author__ = 'meloman'


class PostForm(forms.ModelForm):
    """ Post of blog form """
    class Meta:
        model = Post
        exclude = ('created', 'slug', 'author')

blog/views.py
# coding=utf-8

from django.contrib.auth.models import User
from django.core.paginator import Paginator

from django.core.urlresolvers import reverse
from django.http import Http404
from django.shortcuts import redirect

from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, FormView, View
from blog.forms import PostForm
from blog.models import Post
from utils.decorators import render_to
from utils.funcs import generate_username

__author__ = 'meloman'


class Blog(View):
    def get(self, request):
        return redirect(reverse('blog:blog_page', kwargs={'page': 1, 'username': request.user.username}))


class BlogPage(TemplateView):
    template_name = 'blog/page.html'

    @method_decorator(render_to(template_name))
    def get(self, request, *args, **kwargs):
        try:
            user = User.objects.get(username=kwargs['username'])
        except:
            raise Http404
        else:
            posts = Post.objects.filter(author=user).order_by('created')
            paginator = Paginator(posts, 10)
            return {
                'page': paginator.page(kwargs.get('page', 1)),
                'username': user.username,
            }


class PostPage(TemplateView):
    template_name = 'blog/post.html'

    @method_decorator(render_to(template_name))
    def get(self, request, *args, **kwargs):
        try:
            user = User.objects.get(username=kwargs['username'])
        except:
            raise Http404
        else:
            blog_post = Post.objects.get(slug=kwargs['slug'])
            return {
                'blog_post': blog_post,
                'username': user.username,
            }


class PostAddPage(FormView):
    template_name = 'blog/post_add.html'
    form_class = PostForm

    def get_initial(self):
        self.success_url = reverse('blog:blog_page', kwargs={'page': 1, 'username': self.request.user.username})

    @method_decorator(render_to(template_name))
    def get(self, request, *args, **kwargs):
        return {
            'form': self.form_class,
            'username': self.request.user.username,
        }

    def form_valid(self, form):
        data = form.cleaned_data
        Post.objects.create(
            title=data['title'],
            slug=generate_username(full_name=data['title'], model=Post, property='slug'),
            short_body=data['short_body'],
            body=data['body'],
            author=self.request.user,
            image=data['image'],
        )
        return super(PostAddPage, self).form_valid(form)

templates/blog/_base_blog.html
{% extends '_base.html' %}

{% load bootstrap3 %}
{% load thumbnail %}
{% load i18n %}



{% block header %}
    <div class="panel panel-default blogs-header">
        {% block back_button %}{% endblock %}

        {# Translators: Базовая часть станицы блога. Заголовок шапки #}
        <div>{% trans 'base_blog_page_title' %}</div>

        {% block add_post_button %}{% endblock %}

        <a class="logout-button" href="{% url 'accounts:logout' %}">
            <span class="glyphicon glyphicon-off"></span>
        </a>
    </div>
{% endblock %}

{% block content %}
    {% block blog_content %}{% endblock %}

    {% block pagination %}{% endblock %}
{% endblock %}

{% block footer %}
    <div class="panel panel-default blogs-footer">
        {# Translators: Базовая часть станицы блога. Текст футера #}
        <div>{% trans 'base_blog_page_footer' %}</div>
        <div class="language_choice">
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
                <a class="language-link" href="#">{{ language.code|title }}</a>
                {% if not forloop.last %}/{% endif %}
                <input type="hidden" value="{{ language.code }}">
            {% endfor %}
        </div>

        <form name="changeLanguage" action="{% url 'set_language' %}" method="post" style="display: none">
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" />
            <select name="language">
                <option value="ru" selected="selected"></option>
            </select>
        </form>
    </div>
{% endblock %}

templates/blog/page.html
{% extends 'blog/_base_blog.html' %}

{% load bootstrap3 %}
{% load thumbnail %}


{% block back_button %}
    <a class="back-button" href="{% url 'home' %}">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
{% endblock %}

{% block add_post_button %}
    {% if user.is_authenticated %}
        <a class="add-post-button" href="{% url 'blog:post_add' user.username %}">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
    {% endif %}
{% endblock %}

{% block blog_content %}
    <div class="panel panel-default blogs-content active-pagination">
        {% for post in page %}
            <a href="{% url 'blog:blog_post' username post.slug %}" class="link-post-item">
                <div class="panel panel-primary post-item">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            <span>[{{ post.created|date:'d.m.Y' }}] </span>
                            <span>{{ post.title }}</span>
                        </h3>
                    </div>

                    <div class="panel-body">
                        {% thumbnail post.image "50x50" crop="center" as image %}
                            <img src="{{ image.url }}" alt="">
                        {% endthumbnail %}
                        <span class="short-body">{{ post.short_body }}</span>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

{% block pagination %}
    <div class="panel panel-default pagination-block">
        <nav class="pagination-wrapper">
            <ul class="pagination">
                <li class="{% if not page.has_previous %}disabled{% endif %}">
                    {% if page.has_previous %}
                        <a href="{% if page.has_previous %}{% url 'blog:blog_page' username page.previous_page_number %}{% endif %}">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&laquo;</span>
                    {% endif %}
                </li>
                {% for page_num in page.paginator.page_range %}
                    <li class="{% if page_num == page.number  %}active{% endif %}">
                        <a href="{% url 'blog:blog_page' username page_num %}">{{ page_num }}</a>
                    </li>
                {% endfor %}
                <li class="{% if not page.has_next %}disabled{% endif %}">
                    {% if page.has_next %}
                        <a href="{% if page.has_next %}{% url 'blog:blog_page' username page.next_page_number %}{% endif %}">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% else %}
                        <span aria-hidden="true">&raquo;</span>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

templates/blog/post.html
{% extends 'blog/_base_blog.html' %}

{% load bootstrap3 %}
{% load thumbnail %}



{% block back_button %}
    <a class="back-button" href="{% url 'blog:blog_page' username 1 %}">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
{% endblock %}

{% block blog_content %}
    <div class="panel panel-default blogs-content inactive-pagination">
        <div class="panel panel-primary post-content">
            <div class="panel-heading">
                <h3 class="panel-title">{{ blog_post.title }}
                    <span class="navbar-text navbar-right">[{{ blog_post.created|date:'d.m.Y' }}]</span>
                </h3>

            </div>
            <div class="panel-body">
                {% if blog_post.image %}
                    {% if blog_post.image|is_portrait %}
                        {% thumbnail blog_post.image "x600" crop="top" as image %}
                            <img src="{{ image.url }}" />
                        {% endthumbnail %}
                    {% else %}
                        {% thumbnail blog_post.image "955" crop="top" as image %}
                            <img src="{{ image.url }}" />
                        {% endthumbnail %}
                    {% endif %}
                {% endif %}
                <div class="panel panel-default blog_post_body">
                    <div class="panel-body">
                        {{ blog_post.body|linebreaks }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/blog/post_add.html
{% extends 'blog/_base_blog.html' %}

{% load bootstrap3 %}
{% load thumbnail %}
{% load i18n %}



{% block back_button %}
    <a class="back-button" href="{% url 'blog:blog_page' user.username 1 %}">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
{% endblock %}

{% block blog_content %}
    <div class="panel panel-default blogs-content inactive-pagination">
        <div class="panel panel-default add-post-form">
            <form class="" action="#" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <button class="btn btn-primary" type="submit">
                    {# Translators: Страница добавления поста блога. Кнопка сохранить #}
                    {% trans 'blog_add_post_page_save_button' %}
                </button>
            </form>
        </div>
    </div>
{% endblock %}